### ISSUE TITLE
running on rhel7

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/maestro#18]
@nick-enoent I'm trying to run maestro on x86_64 with

golang-1.15.14-1.el7.x86_64 (epel7)
etcd-3.3.11-2.el7.centos.x86_64 (rhel7 extras) (running as a system service on standard port)
gcc-4.8.5-44.el7.x86_64 (rhel7)
python3-3.6.8-18.el7.x86_64 (rhel7)
python3-etcd (python setup.py install to /usr/local)

maestro_ctrl runs, but I don't end up seeing any data with etcdctl ls -r / (other than test items i put there with etcdctl).
Any thoughts on what's wrong?
I have added print statement before the client put that shows all the data being submitted, and get no exceptions back.

**Comment by nick-enoent** [comment]
@baallan It sounds like you could have 2 instances of etcd running. One that is communicating with maestro, and one running locally that is communicating with etcdctl. What does your etcd.yaml configuration look like? etcdctl will attempt to query a local etcd at 127.0.0.1:2379 by default unless it is configured otherwise.

**Comment by baallan** [comment]
identical result with fresh clone  f963ef9b7627092255565a6483873b55abbea197
